// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.33.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

UuidValue createUuid({dynamic hint}) =>
    RustLib.instance.api.createUuid(hint: hint);

Future<Article> loadArticles({required String page, dynamic hint}) =>
    RustLib.instance.api.loadArticles(page: page, hint: hint);

class Article {
  final int id;
  final String title;
  final Uint8List image;
  final String url;
  final String publisher;
  final Uint8List publisherFavicon;

  const Article({
    required this.id,
    required this.title,
    required this.image,
    required this.url,
    required this.publisher,
    required this.publisherFavicon,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      image.hashCode ^
      url.hashCode ^
      publisher.hashCode ^
      publisherFavicon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Article &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          image == other.image &&
          url == other.url &&
          publisher == other.publisher &&
          publisherFavicon == other.publisherFavicon;
}
